require('dotenv').config();
const express=require('express');
const cors=require('cors');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const mysql=require('mysql2/promise');
const multer=require('multer');
const path=require('path');
const fs=require('fs');

const app=express();
const PORT=Number(process.env.PORT||4000);
const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET';
const pool=mysql.createPool({host:process.env.DB_HOST||'127.0.0.1',port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||'root',password:process.env.DB_PASSWORD||'',database:process.env.DB_NAME||'smart_investment',waitForConnections:true,connectionLimit:10,decimalNumbers:true});
const uploadDir=path.join(__dirname,'uploads','payment-proofs');fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\//.test(file.mimetype))});
const allowedOrigins=(process.env.CORS_ORIGIN||'http://localhost:5173,http://localhost:5174').split(',').map(x=>x.trim());
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.includes(origin))return cb(null,true);cb(new Error('CORS origin not allowed'))}}));
app.use(express.json({limit:'2mb'}));
app.use('/uploads',express.static(path.join(__dirname,'uploads')));

const sign=(payload)=>jwt.sign(payload,JWT_SECRET,{expiresIn:'7d'});
function tokenFrom(req){return (req.headers.authorization||'').replace(/^Bearer\s+/,'')}
function auth(req,res,next){try{const t=tokenFrom(req);if(!t)throw Error();req.auth=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:'Authentication required or session expired.'})}}
function adminOnly(req,res,next){auth(req,res,()=>{if(req.auth.role!=='admin'&&req.auth.role!=='super_admin')return res.status(403).json({error:'Admin access required.'});next()})}
function bad(res,msg){return res.status(400).json({error:msg})}
function ref(prefix){return prefix+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.floor(1000+Math.random()*9000)}
async function audit(adminId,action,targetType,targetId,info){await pool.query('INSERT INTO audit_logs(admin_id,action,target_type,target_id,change_info) VALUES(?,?,?,?,?)',[adminId,action,targetType,targetId,JSON.stringify(info||{})])}
async function setting(key,def=''){const [r]=await pool.query('SELECT setting_value FROM platform_settings WHERE setting_key=?',[key]);return r[0]?.setting_value??def}
async function setSetting(key,value){await pool.query('INSERT INTO platform_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)',[key,String(value)])}

app.get('/api/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:true})}catch(e){res.status(500).json({ok:false,database:false,error:e.message})}});

// Customer authentication
app.post('/api/auth/signup',async(req,res)=>{try{const username=String(req.body.username||'').trim(),password=String(req.body.password||''),refCode=String(req.body.referralCode||'').trim().toUpperCase();if(!/^[a-zA-Z0-9_]{3,60}$/.test(username))return bad(res,'Username must be 3-60 letters, numbers or underscore.');if(password.length<6)return bad(res,'Password must be at least 6 characters.');const [dup]=await pool.query('SELECT id FROM users WHERE username=?',[username]);if(dup.length)return res.status(409).json({error:'Username already exists.'});let referrer=null;if(refCode){const [r]=await pool.query('SELECT id,referral_code FROM users WHERE referral_code=? AND status="active"',[refCode]);if(!r.length)return bad(res,'Invalid referral code.');referrer=r[0]}
 let code;for(let i=0;i<20;i++){const c='SI'+Math.random().toString(36).slice(2,8).toUpperCase();const [x]=await pool.query('SELECT id FROM users WHERE referral_code=?',[c]);if(!x.length){code=c;break}}if(!code)throw Error('Could not generate referral code.');const hash=await bcrypt.hash(password,12);const conn=await pool.getConnection();try{await conn.beginTransaction();const [r]=await conn.query('INSERT INTO users(username,password_hash,referral_code,referred_by_user_id) VALUES(?,?,?,?)',[username,hash,code,referrer?.id||null]);if(referrer)await conn.query('INSERT INTO referrals(referrer_user_id,referred_user_id,referral_code) VALUES(?,?,?)',[referrer.id,r.insertId,code]);await conn.commit();const [u]=await conn.query('SELECT id,username,email,phone,referral_code,balance,referral_earnings,status,created_at FROM users WHERE id=?',[r.insertId]);res.status(201).json({token:sign({id:r.insertId,role:'user',username}),user:u[0]})}catch(e){await conn.rollback();throw e}finally{conn.release()}}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');const [r]=await pool.query('SELECT * FROM users WHERE username=?',[username]);if(!r.length||!(await bcrypt.compare(password,r[0].password_hash)))return res.status(401).json({error:'Invalid username or password.'});if(r[0].status!=='active')return res.status(403).json({error:'Your account is suspended.'});res.json({token:sign({id:r[0].id,role:'user',username:r[0].username}),user:r[0]})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/change-password',auth,async(req,res)=>{try{if(req.auth.role!=='user')return res.status(403).json({error:'Invalid user session.'});const cur=String(req.body.currentPassword||''),next=String(req.body.newPassword||'');if(next.length<6)return bad(res,'New password must be at least 6 characters.');const [r]=await pool.query('SELECT password_hash FROM users WHERE id=?',[req.auth.id]);if(!r.length||!(await bcrypt.compare(cur,r[0].password_hash)))return res.status(401).json({error:'Current password is incorrect.'});await pool.query('UPDATE users SET password_hash=? WHERE id=?',[await bcrypt.hash(next,12),req.auth.id]);res.json({message:'Password changed successfully.'})}catch(e){res.status(500).json({error:e.message})}});

// Public/customer data
app.get('/api/settings/public',async(req,res)=>{try{const [m]=await pool.query('SELECT method,enabled,account_name,account_number,instructions FROM payment_settings ORDER BY id');res.json({methods:m.map(x=>({name:x.method==='easypaisa'?'EasyPaisa':x.method==='jazzcash'?'JazzCash':'Bank Transfer',enabled:!!x.enabled,account_name:x.account_name,account_number:x.account_number,instructions:x.instructions}))})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/plans',async(req,res)=>{try{const [r]=await pool.query('SELECT id,name,amount,daily_rate,validity_days AS duration_days FROM investment_plans WHERE status="active" ORDER BY sort_order,id');res.json(r)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/profile',auth,async(req,res)=>{try{if(req.auth.role!=='user')return res.status(403).json({error:'Invalid user session.'});const [r]=await pool.query('SELECT id,username,email,phone,referral_code,referred_by_user_id,balance,referral_earnings,status,created_at FROM users WHERE id=?',[req.auth.id]);if(!r.length)return res.status(404).json({error:'User not found.'});res.json(r[0])}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/investments',auth,async(req,res)=>{try{const [r]=await pool.query('SELECT i.*,p.name AS plan_name FROM investments i JOIN investment_plans p ON p.id=i.plan_id WHERE i.user_id=? ORDER BY i.id DESC',[req.auth.id]);res.json(r)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/investments',auth,async(req,res)=>{const conn=await pool.getConnection();try{const planId=Number(req.body.planId);if(!Number.isInteger(planId))return bad(res,'Invalid plan.');await conn.beginTransaction();const [p]=await conn.query('SELECT * FROM investment_plans WHERE id=? AND status="active" FOR UPDATE',[planId]);if(!p.length){await conn.rollback();return bad(res,'Investment plan is not active.')}const plan=p[0];const [u]=await conn.query('SELECT balance,status FROM users WHERE id=? FOR UPDATE',[req.auth.id]);if(!u.length||u[0].status!=='active'){await conn.rollback();return res.status(403).json({error:'Account is not active.'})}if(Number(u[0].balance)<Number(plan.amount)){await conn.rollback();return bad(res,'Insufficient balance. Deposit funds first.')}const start=new Date();const end=new Date(start.getTime()+Number(plan.validity_days)*86400000);const [i]=await conn.query('INSERT INTO investments(user_id,plan_id,amount,daily_rate,validity_days,start_at,end_at) VALUES(?,?,?,?,?,?,?)',[req.auth.id,plan.id,plan.amount,plan.daily_rate,plan.validity_days,start,end]);await conn.query('UPDATE users SET balance=balance-? WHERE id=?',[plan.amount,req.auth.id]);await conn.query('INSERT INTO transactions(user_id,type,amount,reference,status,description) VALUES(?,?,?,?,?,?)',[req.auth.id,'investment',plan.amount,ref('INV'),'completed','Investment created']);await conn.query('INSERT INTO notifications(user_id,title,message) VALUES(?,?,?)',[req.auth.id,'Investment started',`${plan.name} investment has been created successfully.`]);await conn.commit();res.status(201).json({message:'Investment created successfully.',investmentId:i.insertId})}catch(e){await conn.rollback();res.status(500).json({error:e.message})}finally{conn.release()}});
app.post('/api/deposits',auth,upload.single('paymentScreenshot'),async(req,res)=>{try{const amount=Number(req.body.amount),method=String(req.body.method||'').trim().toLowerCase(),reference=String(req.body.reference||'').trim();let planAmount=null;if(req.body.planId){const [p]=await pool.query('SELECT amount FROM investment_plans WHERE id=? AND status="active"',[Number(req.body.planId)]);planAmount=p[0]?.amount}const finalAmount=amount||Number(planAmount);if(!(finalAmount>0))return bad(res,'Valid deposit amount is required.');if(!['easypaisa','jazzcash','bank'].includes(method))return bad(res,'Invalid payment method.');if(!reference&&!req.file)return bad(res,'Transaction reference or screenshot is required.');if(reference){const [x]=await pool.query('SELECT id FROM deposits WHERE reference=?',[reference]);if(x.length)return res.status(409).json({error:'This transaction reference has already been submitted.'})}const shot=req.file?'/uploads/payment-proofs/'+path.basename(req.file.path):null;const [r]=await pool.query('INSERT INTO deposits(user_id,amount,method,reference,screenshot) VALUES(?,?,?,?,?)',[req.auth.id,finalAmount,method,reference||null,shot]);await pool.query('INSERT INTO transactions(user_id,type,amount,reference,status,description) VALUES(?,?,?,?,?,?)',[req.auth.id,'deposit',finalAmount,'DEP-'+r.insertId,'pending','Deposit submitted for verification']);res.status(201).json({message:'Deposit request submitted for admin review.',id:r.insertId})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/transactions',auth,async(req,res)=>{try{const [r]=await pool.query('SELECT id,type,amount,reference,status,description,created_at FROM transactions WHERE user_id=? ORDER BY id DESC',[req.auth.id]);res.json(r)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/referrals',auth,async(req,res)=>{try{const [u]=await pool.query('SELECT referral_code,referral_earnings FROM users WHERE id=?',[req.auth.id]);const [r]=await pool.query('SELECT u.username,u.created_at,COALESCE(rr.status,"pending") reward_status FROM referrals rf JOIN users u ON u.id=rf.referred_user_id LEFT JOIN referral_rewards rr ON rr.referral_id=rf.id WHERE rf.referrer_user_id=? ORDER BY rf.id DESC',[req.auth.id]);res.json({code:u[0].referral_code,earnings:u[0].referral_earnings,total:r.length,users:r})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/withdrawals',auth,async(req,res)=>{try{const amount=Number(req.body.amount),method=String(req.body.method||'').trim(),account=String(req.body.account||'').trim();if(!(amount>0)||!method||account.length<4)return bad(res,'Valid amount, method and account details are required.');const [u]=await pool.query('SELECT balance,status FROM users WHERE id=?',[req.auth.id]);if(!u.length||u[0].status!=='active')return res.status(403).json({error:'Account is not active.'});const [p]=await pool.query('SELECT COALESCE(SUM(amount),0) reserved FROM withdrawals WHERE user_id=? AND status IN ("pending","processing")',[req.auth.id]);const available=Number(u[0].balance)-Number(p[0].reserved);if(amount>available)return bad(res,'Insufficient available balance.');const reference=ref('WD');const [r]=await pool.query('INSERT INTO withdrawals(user_id,amount,method,account_details,reference) VALUES(?,?,?,?,?)',[req.auth.id,amount,method,account,reference]);await pool.query('INSERT INTO transactions(user_id,type,amount,reference,status,description) VALUES(?,?,?,?,?,?)',[req.auth.id,'withdrawal',amount,reference,'pending','Withdrawal request submitted']);res.status(201).json({message:'Withdrawal request submitted.',id:r.insertId})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/withdrawals',auth,async(req,res)=>{try{const [r]=await pool.query('SELECT id,amount,method,account_details,reference,status,created_at,reviewed_at FROM withdrawals WHERE user_id=? ORDER BY id DESC',[req.auth.id]);res.json(r)}catch(e){res.status(500).json({error:e.message})}});

// Admin auth
app.post('/api/admin/auth/login',async(req,res)=>{try{const login=String(req.body.login||'').trim(),password=String(req.body.password||'');const [r]=await pool.query('SELECT * FROM admins WHERE username=? OR email=? LIMIT 1',[login,login]);if(!r.length||!(await bcrypt.compare(password,r[0].password_hash)))return res.status(401).json({error:'Invalid admin credentials.'});if(r[0].status!=='active')return res.status(403).json({error:'Admin account is disabled.'});res.json({token:sign({id:r[0].id,role:r[0].role,username:r[0].username}),admin:{id:r[0].id,username:r[0].username,email:r[0].email,role:r[0].role}})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/me',adminOnly,async(req,res)=>{const [r]=await pool.query('SELECT id,username,email,role,status FROM admins WHERE id=?',[req.auth.id]);res.json(r[0])});

// Admin dashboard
app.get('/api/admin/dashboard',adminOnly,async(req,res)=>{try{const [[u]] =await pool.query('SELECT COUNT(*) total FROM users');const [[d]] =await pool.query('SELECT COALESCE(SUM(amount),0) total FROM deposits WHERE status="approved"');const [[pd]]=await pool.query('SELECT COUNT(*) total FROM deposits WHERE status="pending"');const [[pw]]=await pool.query('SELECT COUNT(*) total FROM withdrawals WHERE status IN ("pending","processing")');const [[ai]]=await pool.query('SELECT COUNT(*) total FROM investments WHERE status="active"');const [[tx]]=await pool.query('SELECT COUNT(*) total FROM transactions');const [recent]=await pool.query('SELECT d.*,u.username FROM deposits d JOIN users u ON u.id=d.user_id ORDER BY d.id DESC LIMIT 7');const [plans]=await pool.query('SELECT p.id,p.name,COUNT(i.id) cnt FROM investment_plans p LEFT JOIN investments i ON i.plan_id=p.id GROUP BY p.id,p.name ORDER BY cnt DESC LIMIT 3');const totalPlan=plans.reduce((a,x)=>a+Number(x.cnt),0)||1;res.json({totalUsers:u.total,totalDeposits:d.total,pendingDeposits:pd.total,pendingWithdrawals:pw.total,activeInvestments:ai.total,totalTransactions:tx.total,investmentShare:65,planBreakdown:plans.map(x=>Math.round(Number(x.cnt)/totalPlan*100)),recentDeposits:recent})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/users',adminOnly,async(req,res)=>{try{const [r]=await pool.query('SELECT id,username,email,phone,referral_code,balance,referral_earnings,created_at,status FROM users ORDER BY id DESC');res.json(r)}catch(e){res.status(500).json({error:e.message})}});
app.patch('/api/admin/users/:id/status',adminOnly,async(req,res)=>{try{const status=req.body.status;if(!['active','suspended'].includes(status))return bad(res,'Invalid status.');await pool.query('UPDATE users SET status=? WHERE id=?',[status,req.params.id]);await audit(req.auth.id,'UPDATE_USER_STATUS','user',req.params.id,{status});res.json({message:'User status updated.'})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/deposits',adminOnly,async(req,res)=>{try{const [r]=await pool.query('SELECT d.*,u.username,ps.method AS configured_method FROM deposits d JOIN users u ON u.id=d.user_id LEFT JOIN payment_settings ps ON ps.method=d.method ORDER BY d.id DESC');res.json(r.map(x=>({...x,method:x.method,reference:x.reference,screenshot:x.screenshot}))) }catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/deposits/:id/approve',adminOnly,async(req,res)=>{const c=await pool.getConnection();try{await c.beginTransaction();const [d]=await c.query('SELECT * FROM deposits WHERE id=? FOR UPDATE',[req.params.id]);if(!d.length||d[0].status!=='pending'){await c.rollback();return bad(res,'Deposit is no longer pending.')}const dep=d[0];await c.query('UPDATE deposits SET status="approved",reviewed_by=?,reviewed_at=NOW() WHERE id=?',[req.auth.id,dep.id]);const [tx]=await c.query('SELECT id FROM transactions WHERE user_id=? AND type="deposit" AND reference=? LIMIT 1',[dep.user_id,'DEP-'+dep.id]);await c.query('UPDATE users SET balance=balance+? WHERE id=?',[dep.amount,dep.user_id]);if(tx.length)await c.query('UPDATE transactions SET status="approved",amount=?,description=? WHERE id=?',[dep.amount,'Deposit approved and credited',tx[0].id]);else await c.query('INSERT INTO transactions(user_id,type,amount,reference,status,description) VALUES(?,?,?,?,?,?)',[dep.user_id,'deposit',dep.amount,'DEP-'+dep.id,'approved','Deposit approved and credited']);await c.query('INSERT INTO notifications(user_id,title,message) VALUES(?,?,?)',[dep.user_id,'Deposit approved',`Your deposit of PKR ${Number(dep.amount).toLocaleString()} has been approved.`]);const rate=Number(await setting('referral_rate','5'));if(rate>0){const [rf]=await c.query('SELECT * FROM referrals WHERE referred_user_id=? AND status="valid"',[dep.user_id]);if(rf.length){const reward=Number(dep.amount)*rate/100;await c.query('INSERT INTO referral_rewards(referral_id,referrer_user_id,referred_user_id,source_deposit_id,amount,status,paid_at) VALUES(?,?,?,?,?,"paid",NOW())',[rf[0].id,rf[0].referrer_user_id,dep.user_id,dep.id,reward]);await c.query('UPDATE users SET balance=balance+?,referral_earnings=referral_earnings+? WHERE id=?',[reward,reward,rf[0].referrer_user_id]);await c.query('INSERT INTO transactions(user_id,type,amount,reference,status,description) VALUES(?,?,?,?,?,?)',[rf[0].referrer_user_id,'referral_reward',reward,ref('REF'),'completed','Referral reward for approved deposit']);}}await c.commit();await audit(req.auth.id,'APPROVE_DEPOSIT','deposit',dep.id,{amount:dep.amount,user_id:dep.user_id});res.json({message:'Deposit approved and credited.'})}catch(e){await c.rollback();res.status(500).json({error:e.message})}finally{c.release()}});
app.post('/api/admin/deposits/:id/reject',adminOnly,async(req,res)=>{try{const reason=String(req.body.reason||'Rejected by admin');const [r]=await pool.query('UPDATE deposits SET status="rejected",rejection_reason=?,reviewed_by=?,reviewed_at=NOW() WHERE id=? AND status="pending"',[reason,req.auth.id,req.params.id]);if(!r.affectedRows)return bad(res,'Deposit is no longer pending.');await pool.query('UPDATE transactions SET status="rejected",description=? WHERE type="deposit" AND reference=?',[reason,'DEP-'+req.params.id]);await audit(req.auth.id,'REJECT_DEPOSIT','deposit',req.params.id,{reason});res.json({message:'Deposit rejected.'})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/withdrawals',adminOnly,async(req,res)=>{try{const [r]=await pool.query('SELECT w.*,u.username,u.balance FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.id DESC');res.json(r.map(x=>({...x,available_balance:Number(x.balance)})))}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/withdrawals/:id/processing',adminOnly,async(req,res)=>{try{const [r]=await pool.query('UPDATE withdrawals SET status="processing",reviewed_by=?,reviewed_at=NOW() WHERE id=? AND status="pending"',[req.auth.id,req.params.id]);if(!r.affectedRows)return bad(res,'Withdrawal is no longer pending.');await audit(req.auth.id,'PROCESS_WITHDRAWAL','withdrawal',req.params.id,{});res.json({message:'Withdrawal marked processing.'})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/withdrawals/:id/approve',adminOnly,async(req,res)=>{const c=await pool.getConnection();try{await c.beginTransaction();const [w]=await c.query('SELECT * FROM withdrawals WHERE id=? FOR UPDATE',[req.params.id]);if(!w.length||!['pending','processing'].includes(w[0].status)){await c.rollback();return bad(res,'Withdrawal cannot be completed.')}const wd=w[0];const [u]=await c.query('SELECT balance FROM users WHERE id=? FOR UPDATE',[wd.user_id]);if(Number(u[0].balance)<Number(wd.amount)){await c.rollback();return bad(res,'User balance is no longer sufficient.')}await c.query('UPDATE users SET balance=balance-? WHERE id=?',[wd.amount,wd.user_id]);await c.query('UPDATE withdrawals SET status="completed",reviewed_by=?,reviewed_at=NOW() WHERE id=?',[req.auth.id,wd.id]);await c.query('UPDATE transactions SET status="completed",description=? WHERE user_id=? AND type="withdrawal" AND reference=?',[ 'Withdrawal completed',wd.user_id,wd.reference]);await c.query('INSERT INTO notifications(user_id,title,message) VALUES(?,?,?)',[wd.user_id,'Withdrawal completed',`Your withdrawal of PKR ${Number(wd.amount).toLocaleString()} has been completed.`]);await c.commit();await audit(req.auth.id,'COMPLETE_WITHDRAWAL','withdrawal',wd.id,{amount:wd.amount});res.json({message:'Withdrawal completed.'})}catch(e){await c.rollback();res.status(500).json({error:e.message})}finally{c.release()}});
app.post('/api/admin/withdrawals/:id/reject',adminOnly,async(req,res)=>{try{const reason=String(req.body.reason||'Rejected by admin');const [r]=await pool.query('UPDATE withdrawals SET status="rejected",rejection_reason=?,reviewed_by=?,reviewed_at=NOW() WHERE id=? AND status IN ("pending","processing")',[reason,req.auth.id,req.params.id]);if(!r.affectedRows)return bad(res,'Withdrawal cannot be rejected.');await pool.query('UPDATE transactions SET status="rejected",description=? WHERE type="withdrawal" AND reference=(SELECT reference FROM withdrawals WHERE id=?)',[reason,req.params.id]);await audit(req.auth.id,'REJECT_WITHDRAWAL','withdrawal',req.params.id,{reason});res.json({message:'Withdrawal rejected.'})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/plans',adminOnly,async(req,res)=>{try{const [r]=await pool.query('SELECT id,name,amount,daily_rate,validity_days AS duration_days,status,sort_order FROM investment_plans ORDER BY sort_order,id');res.json(r.map(x=>({...x,active:x.status==='active'})))}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/admin/plans/:id',adminOnly,async(req,res)=>{try{const name=String(req.body.name||'').trim(),amount=Number(req.body.amount),rate=Number(req.body.daily_rate),days=Number(req.body.validity_days);if(!name||!(amount>0)||rate<0||!(days>0))return bad(res,'Invalid plan values.');await pool.query('UPDATE investment_plans SET name=?,amount=?,daily_rate=?,validity_days=? WHERE id=?',[name,amount,rate,days,req.params.id]);await audit(req.auth.id,'UPDATE_PLAN','investment_plan',req.params.id,{name,amount,rate,days});res.json({message:'Plan saved.'})}catch(e){res.status(500).json({error:e.message})}});
app.patch('/api/admin/plans/:id',adminOnly,async(req,res)=>{try{const status=req.body.active?'active':'disabled';await pool.query('UPDATE investment_plans SET status=? WHERE id=?',[status,req.params.id]);await audit(req.auth.id,status==='active'?'ENABLE_PLAN':'DISABLE_PLAN','investment_plan',req.params.id,{status});res.json({message:'Plan status updated.'})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/payment-settings',adminOnly,async(req,res)=>{try{const [r]=await pool.query('SELECT method,enabled,account_name,account_number,instructions FROM payment_settings');const o={};r.forEach(x=>o[x.method]=x);res.json({easypaisa:o.easypaisa||{},jazzcash:o.jazzcash||{},bank:o.bank||{}})}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/admin/payment-settings',adminOnly,async(req,res)=>{try{for(const [method,v] of Object.entries(req.body)){if(!['easypaisa','jazzcash','bank'].includes(method))continue;await pool.query('INSERT INTO payment_settings(method,enabled,account_name,account_number,instructions) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE enabled=VALUES(enabled),account_name=VALUES(account_name),account_number=VALUES(account_number),instructions=VALUES(instructions)',[method,!!v.enabled,String(v.account_name||''),String(v.account_number||''),String(v.instructions||'')])}await audit(req.auth.id,'UPDATE_PAYMENT_SETTINGS','payment_settings','all',req.body);res.json({message:'Payment settings saved.'})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/transactions',adminOnly,async(req,res)=>{try{const [r]=await pool.query('SELECT t.*,u.username FROM transactions t JOIN users u ON u.id=t.user_id ORDER BY t.id DESC');res.json(r)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/referrals',adminOnly,async(req,res)=>{try{const [[a]]=await pool.query('SELECT COUNT(*) total FROM referrals');const [[p]]=await pool.query('SELECT COALESCE(SUM(amount),0) total FROM referral_rewards WHERE status="paid"');const [[q]]=await pool.query('SELECT COALESCE(SUM(amount),0) total FROM referral_rewards WHERE status="pending"');const [[iv]]=await pool.query('SELECT COUNT(*) total FROM referrals WHERE status="invalid"');const [rows]=await pool.query('SELECT u1.username referrer,u2.username referred,r.referral_code,COALESCE(rr.amount,0) reward,COALESCE(rr.status,"pending") status FROM referrals r JOIN users u1 ON u1.id=r.referrer_user_id JOIN users u2 ON u2.id=r.referred_user_id LEFT JOIN referral_rewards rr ON rr.referral_id=r.id ORDER BY r.id DESC');res.json({total:a.total,rewardPaid:p.total,pendingRewards:q.total,invalid:iv.total,rows})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/settings',adminOnly,async(req,res)=>{try{res.json({platform_name:await setting('platform_name','SmartInvestment'),support_email:await setting('support_email','support@example.com'),referral_rate:Number(await setting('referral_rate','5')),logs:await (async()=>{const [r]=await pool.query('SELECT a.action,a.created_at,ad.username AS admin FROM audit_logs a JOIN admins ad ON ad.id=a.admin_id ORDER BY a.id DESC LIMIT 12');return r})()})}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/admin/settings',adminOnly,async(req,res)=>{try{await setSetting('platform_name',req.body.platform_name||'SmartInvestment');await setSetting('support_email',req.body.support_email||'');const rate=Number(req.body.referral_rate);if(!(rate>=0&&rate<=100))return bad(res,'Referral rate must be between 0 and 100.');await setSetting('referral_rate',rate);await audit(req.auth.id,'UPDATE_PLATFORM_SETTINGS','platform_settings','global',{platform_name:req.body.platform_name,support_email:req.body.support_email,referral_rate:rate});res.json({message:'Settings saved.'})}catch(e){res.status(500).json({error:e.message})}});

app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:err.message||'Server error.'})});
app.listen(PORT,()=>console.log(`SmartInvestment API running on http://localhost:${PORT}`));
